package commands

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"text/template"

	"github.com/spf13/cobra"
)

// hookScript is the shell script content written to .git/hooks/pre-commit.
// It uses a POSIX-compliant shebang so it works on Linux, macOS, and Termux.
const hookScript = `#!/usr/bin/env sh
# ┌─────────────────────────────────────────────────────────────────────┐
# │  SENTINEL — Pre-Commit Security Hook                                 │
# │  Auto-generated by: sentinel install                                 │
# │  Do not edit this file manually. Re-run sentinel install to update. │
# └─────────────────────────────────────────────────────────────────────┘

SENTINEL_BIN="{{.BinPath}}"

# If the binary path is not set or not found, look on PATH.
if [ -z "$SENTINEL_BIN" ] || [ ! -x "$SENTINEL_BIN" ]; then
    SENTINEL_BIN=$(command -v sentinel 2>/dev/null)
fi

if [ -z "$SENTINEL_BIN" ]; then
    echo "sentinel: hook is installed but the 'sentinel' binary was not found." >&2
    echo "sentinel: install it via 'go install github.com/sentinel-cli/sentinel/cmd/sentinel@latest'" >&2
    exit 1
fi

exec "$SENTINEL_BIN" run "$@"
`

// NewInstallCmd builds the `sentinel install` sub-command.
func NewInstallCmd() *cobra.Command {
	var (
		global  bool
		repoDir string
		force   bool
	)

	cmd := &cobra.Command{
		Use:   "install",
		Short: "Install the pre-commit hook into a git repository",
		Long: `Install writes a pre-commit hook script into .git/hooks/pre-commit.

  Local install (default):
    Installs the hook for the current git repository only.

  Global install (--global):
    Configures git's core.hooksPath to point to a global hooks directory
    (~/.config/sentinel/hooks) so the hook applies to ALL repositories on
    this machine without requiring per-repository installation.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if global {
				return installGlobal(force)
			}
			return installLocal(repoDir, force)
		},
	}

	cmd.Flags().BoolVar(&global, "global", false, "install globally for all repositories")
	cmd.Flags().StringVar(&repoDir, "repo", ".", "path to the git repository root")
	cmd.Flags().BoolVarP(&force, "force", "f", false, "overwrite an existing hook without prompting")

	return cmd
}

// installLocal writes the hook into <repoDir>/.git/hooks/pre-commit.
func installLocal(repoDir string, force bool) error {
	gitDir := filepath.Join(repoDir, ".git")
	if _, err := os.Stat(gitDir); os.IsNotExist(err) {
		return fmt.Errorf("%q is not a git repository (no .git directory found)", repoDir)
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("cannot create hooks directory: %w", err)
	}

	hookPath := filepath.Join(hooksDir, "pre-commit")
	return writeHookScript(hookPath, force)
}

// installGlobal sets core.hooksPath and writes the hook to the global dir.
func installGlobal(force bool) error {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("cannot determine home directory: %w", err)
	}

	globalHooksDir := filepath.Join(homeDir, ".config", "sentinel", "hooks")
	if err := os.MkdirAll(globalHooksDir, 0o755); err != nil {
		return fmt.Errorf("cannot create global hooks directory: %w", err)
	}

	hookPath := filepath.Join(globalHooksDir, "pre-commit")
	if err := writeHookScript(hookPath, force); err != nil {
		return err
	}

	// Set git's global hooksPath.
	if err := runGitConfig("core.hooksPath", globalHooksDir); err != nil {
		return fmt.Errorf("could not set git core.hooksPath: %w", err)
	}

	fmt.Printf("✔ Sentinel installed globally.\n")
	fmt.Printf("  Global hooks directory: %s\n", globalHooksDir)
	fmt.Printf("  All git repositories on this machine are now protected.\n")
	return nil
}

// writeHookScript renders the hook template and writes it to hookPath.
func writeHookScript(hookPath string, force bool) error {
	if !force {
		if _, err := os.Stat(hookPath); err == nil {
			return fmt.Errorf(
				"a pre-commit hook already exists at %q (use --force to overwrite it)", hookPath)
		}
	}

	binPath, err := currentBinaryPath()
	if err != nil {
		binPath = "" // Will fall back to PATH lookup at hook runtime.
	}

	tmpl, err := template.New("hook").Parse(hookScript)
	if err != nil {
		return fmt.Errorf("internal template error: %w", err)
	}

	f, err := os.OpenFile(hookPath, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o755)
	if err != nil {
		return fmt.Errorf("cannot write hook to %q: %w", hookPath, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, struct{ BinPath string }{BinPath: binPath}); err != nil {
		return fmt.Errorf("cannot render hook script: %w", err)
	}

	fmt.Printf("✔ Sentinel hook installed at: %s\n", hookPath)
	return nil
}

// currentBinaryPath returns the absolute path of the running sentinel binary.
func currentBinaryPath() (string, error) {
	exe, err := os.Executable()
	if err != nil {
		return "", err
	}
	abs, err := filepath.EvalSymlinks(exe)
	if err != nil {
		return exe, nil
	}
	return abs, nil
}

// runGitConfig wraps `git config --global key value`.
func runGitConfig(key, value string) error {
	var cmd string
	if runtime.GOOS == "windows" {
		cmd = "git"
	} else {
		cmd = "git"
	}
	return runCommand(cmd, "config", "--global", key, value)
}
